export const HOME_AUTH: string = '/'
export const AUTH: string = '/auth'
export const DETAILS: string = '/posts/:id'
export const SUBSCRIBES: string = '/subscribes'
export const BOOKMARKS: string = '/bookmarks'
