export const HOME_AUTH: string = '/'
export const AUTH: string = '/auth'
export const DETAILS: string = '/posts/:id'
export const SUBSCRIBES: string = '/subscribes'
export const BOOKMARKS: string = '/bookmarks'
export const USER_INFO: string = '/user/:id'
export const FOUND_ITEMS: string = '/results?query='
